-- ============================================================
-- V11__catalogo_materiales.sql
-- Reemplaza el catalogo basico de materiales (36 de V2) por el
-- catalogo completo de 281 materiales predefinidos.
-- Los IDs quedan deterministas (1..281) para que el futuro seed
-- de tratamientos predefinidos pueda referenciarlos por nombre.
-- ============================================================

DELETE FROM Materiales;
DELETE FROM sqlite_sequence WHERE name = 'Materiales';

INSERT INTO Materiales (Nombre, Unidad, Estado) VALUES
  ('Ácido fluorhídrico', 'frasco', 1),
  ('Ácido fosfórico', 'frasco', 1),
  ('Ácido grabador', 'frasco', 1),
  ('Acondicionador de tejido', 'frasco', 1),
  ('Acrílico 59', 'kit', 1),
  ('Acrílico 62', 'kit', 1),
  ('Acrílico 65', 'kit', 1),
  ('Acrílico líquido monómero', 'frasco', 1),
  ('Acrílico patrón (Pattern Resin)', 'kit', 1),
  ('Acrílico rosado', 'kit', 1),
  ('Acrílico transparente', 'kit', 1),
  ('Adhesivo', 'frasco', 1),
  ('Adhesivo Mucopren', 'frasco', 1),
  ('Agua oxigenada', 'frasco', 1),
  ('Aguja corta', 'unidad', 1),
  ('Aguja extra corta', 'unidad', 1),
  ('Aguja larga', 'unidad', 1),
  ('Aguja Navitip', 'unidad', 1),
  ('Alambre', 'unidad', 1),
  ('Alambre 0.8', 'unidad', 1),
  ('Alambre 0.9', 'unidad', 1),
  ('Alambre de ligadura', 'unidad', 1),
  ('Alcohol puro 70°', 'frasco', 1),
  ('Alcohol yodado', 'frasco', 1),
  ('Alginato', 'bolsa', 1),
  ('Algodón 500 g', 'bolsa', 1),
  ('Alveogil', 'frasco', 1),
  ('Amonio cuaternario', 'frasco', 1),
  ('Anestesia con epinefrina', 'cartucho', 1),
  ('Anestesia sin epinefrina', 'cartucho', 1),
  ('Anestesia tópica', 'frasco', 1),
  ('Arco de dique de goma', 'unidad', 1),
  ('Arco extraoral', 'unidad', 1),
  ('Arco Niti', 'unidad', 1),
  ('Azul de metileno', 'frasco', 1),
  ('Bajalengua', 'paquete', 1),
  ('Bandas', 'unidad', 1),
  ('Bata de cirujano', 'unidad', 1),
  ('Benzocaína', 'frasco', 1),
  ('Bio-C Sealer', 'kit', 1),
  ('Bisacril', 'kit', 1),
  ('Bolsa de chupete', 'unidad', 1),
  ('Botas quirúrgicas', 'par', 1),
  ('Brackets', 'unidad', 1),
  ('Brackets S-I', 'unidad', 1),
  ('Brackets superiores', 'unidad', 1),
  ('Caja roja punzocortante', 'unidad', 1),
  ('Campo descartable', 'paquete', 1),
  ('Campo fenestrado', 'paquete', 1),
  ('Campo simple', 'paquete', 1),
  ('Cánula de succión', 'unidad', 1),
  ('Caucho de goma', 'unidad', 1),
  ('Cemento para carillas Allcem A1', 'kit', 1),
  ('Cemento para carillas Allcem Trans', 'kit', 1),
  ('Cemento para cementación', 'kit', 1),
  ('Cemento policarboxilato', 'kit', 1),
  ('Cemento quirúrgico', 'kit', 1),
  ('Cemento RelyX U200', 'kit', 1),
  ('Cemento RelyX Ultimate', 'kit', 1),
  ('Cemento Variolink', 'kit', 1),
  ('Cera amarilla', 'caja', 1),
  ('Cera base', 'caja', 1),
  ('Cera calibrada', 'caja', 1),
  ('Cera Cavex', 'caja', 1),
  ('Cinta celuloide', 'caja', 1),
  ('Cinta matriz metálica', 'caja', 1),
  ('Clorhexidina', 'frasco', 1),
  ('Coltosol', 'frasco', 1),
  ('Conos de gutapercha', 'caja', 1),
  ('Conos de papel N° 40', 'caja', 1),
  ('Coronas de acero', 'unidad', 1),
  ('Cubeta para flúor', 'unidad', 1),
  ('Cuñas de madera', 'caja', 1),
  ('Desobturador', 'unidad', 1),
  ('Detergente enzimático', 'sobre', 1),
  ('Dique de goma', 'hoja', 1),
  ('Disyuntor Hyrax', 'unidad', 1),
  ('Disyuntor N° 11', 'unidad', 1),
  ('Disyuntor N° 13', 'unidad', 1),
  ('Disyuntor N° 6', 'unidad', 1),
  ('Duralay', 'kit', 1),
  ('Duralay 62', 'kit', 1),
  ('Duralay 65', 'kit', 1),
  ('Duralay rojo', 'kit', 1),
  ('Dycal', 'frasco', 1),
  ('EDTA', 'frasco', 1),
  ('Elásticos intermaxilares', 'paquete', 1),
  ('Endo Ice', 'unidad', 1),
  ('Escobilla interproximal', 'unidad', 1),
  ('Escobilla profiláctica', 'unidad', 1),
  ('Eugenato', 'frasco', 1),
  ('Eugenol', 'frasco', 1),
  ('Fibra de vidrio 0.5', 'unidad', 1),
  ('Fibra de vidrio 1', 'unidad', 1),
  ('Fibra de vidrio 2', 'unidad', 1),
  ('Flúor', 'frasco', 1),
  ('Flúor barniz', 'frasco', 1),
  ('Flúor barniz Climpro', 'frasco', 1),
  ('Flúor neutro', 'frasco', 1),
  ('Formocresol', 'frasco', 1),
  ('Fresa de alta velocidad', 'unidad', 1),
  ('Fresa de baja velocidad', 'unidad', 1),
  ('Fresa de desgaste', 'unidad', 1),
  ('Fundente', 'frasco', 1),
  ('Gasa', 'paquete', 1),
  ('Gasa bucal', 'paquete', 1),
  ('Gasa por paquete', 'paquete', 1),
  ('Gasa x 10 unidades', 'paquete', 1),
  ('Gasa x 5 unidades', 'paquete', 1),
  ('GC Fuji II', 'frasco', 1),
  ('GC Fuji IX', 'frasco', 1),
  ('Gingifast', 'kit', 1),
  ('Glicerina', 'frasco', 1),
  ('Godiva en barra', 'unidad', 1),
  ('Gorro cirujano', 'caja', 1),
  ('Gorro de enfermera', 'caja', 1),
  ('Grapas de dique', 'caja', 1),
  ('Guantes descartables L', 'caja', 1),
  ('Guantes descartables M', 'caja', 1),
  ('Guantes descartables S', 'caja', 1),
  ('Guantes descartables XS', 'caja', 1),
  ('Guantes quirúrgicos 6 1/2', 'caja', 1),
  ('Guantes quirúrgicos 7', 'caja', 1),
  ('Guantes quirúrgicos 7 1/2', 'caja', 1),
  ('Gutapercha en barra', 'caja', 1),
  ('Hemocoldágeno', 'frasco', 1),
  ('Hemotam', 'frasco', 1),
  ('Hibiclens', 'frasco', 1),
  ('Hidróxido de calcio', 'frasco', 1),
  ('Hilo de sutura nylon 4/0', 'sobre', 1),
  ('Hilo de sutura nylon 5/0', 'sobre', 1),
  ('Hilo de sutura poliglicólico 4/0', 'sobre', 1),
  ('Hilo de sutura poliglicólico 5/0', 'sobre', 1),
  ('Hilo de sutura seda trenzada 3/0', 'sobre', 1),
  ('Hilo dental', 'unidad', 1),
  ('Hilo retractor 0', 'unidad', 1),
  ('Hilo retractor 00', 'unidad', 1),
  ('Hilo retractor 000', 'unidad', 1),
  ('Hipoclorito de sodio', 'frasco', 1),
  ('Hisol', 'frasco', 1),
  ('Hisopos', 'paquete', 1),
  ('Hoja de bisturí N° 11', 'unidad', 1),
  ('Hoja de bisturí N° 12', 'unidad', 1),
  ('Hoja de bisturí N° 15', 'unidad', 1),
  ('Hoja de bisturí N° 15C', 'unidad', 1),
  ('Ionómero de base', 'frasco', 1),
  ('Ionómero de cementación Ketac', 'frasco', 1),
  ('Ionómero de cementación Meron', 'frasco', 1),
  ('Ionómero de reconstrucción Ketac', 'frasco', 1),
  ('Ionómero Glass Liners', 'frasco', 1),
  ('Ionómero Vitrebond', 'frasco', 1),
  ('Ionómero Vitremer', 'frasco', 1),
  ('Jeringa carpule', 'unidad', 1),
  ('Jeringa descartable 10 ml', 'unidad', 1),
  ('Jeringa descartable 20 ml', 'unidad', 1),
  ('Jeringa descartable 5 ml', 'unidad', 1),
  ('Jeringa tuberculina', 'unidad', 1),
  ('Ketac Molar', 'frasco', 1),
  ('Ketac Universal', 'frasco', 1),
  ('Liga metálica', 'unidad', 1),
  ('Ligas intraorales', 'paquete', 1),
  ('Ligas separadoras', 'paquete', 1),
  ('Lip Bumper', 'unidad', 1),
  ('Líquido fijador', 'frasco', 1),
  ('Líquido revelador', 'frasco', 1),
  ('Mandil descartable', 'unidad', 1),
  ('Mandil quirúrgico', 'unidad', 1),
  ('Mangas quirúrgicas', 'par', 1),
  ('Máscara facial', 'unidad', 1),
  ('Mascarilla descartable', 'caja', 1),
  ('Mascarilla KN95', 'caja', 1),
  ('Mentonera', 'unidad', 1),
  ('Microbrush', 'unidad', 1),
  ('Monómero', 'frasco', 1),
  ('MTA', 'frasco', 1),
  ('Mucopren', 'kit', 1),
  ('Neociler Flo', 'frasco', 1),
  ('Neoputy', 'kit', 1),
  ('Oclufast', 'kit', 1),
  ('Orange Wash + activador', 'kit', 1),
  ('Orto-Bite', 'unidad', 1),
  ('Óxido de aluminio', 'frasco', 1),
  ('Óxido de zinc + eugenol', 'frasco', 1),
  ('Papel absorbente', 'caja', 1),
  ('Papel articular', 'caja', 1),
  ('Papel articular arcada completa', 'caja', 1),
  ('Papel crepado x 2 pliegos', 'paquete', 1),
  ('Papel crepado x 4 pliegos', 'paquete', 1),
  ('Papel higiénico', 'rollo', 1),
  ('Papel toalla', 'rollo', 1),
  ('Paramonoclorofenol', 'frasco', 1),
  ('Pasta profiláctica', 'frasco', 1),
  ('Pastilla reveladora', 'unidad', 1),
  ('Pelex', 'unidad', 1),
  ('Piedra pómez', 'frasco', 1),
  ('Polvo transparente', 'frasco', 1),
  ('Provinol', 'kit', 1),
  ('Punta diamantada', 'unidad', 1),
  ('Radiografía', 'unidad', 1),
  ('Resina Body', 'jeringa', 1),
  ('Resina Body Esmalte A1', 'jeringa', 1),
  ('Resina Body Esmalte A2', 'jeringa', 1),
  ('Resina Body Shade', 'jeringa', 1),
  ('Resina compuesta', 'jeringa', 1),
  ('Resina Enamel A3', 'jeringa', 1),
  ('Resina fluida A1', 'jeringa', 1),
  ('Resina fluida A2', 'jeringa', 1),
  ('Resina fluida B2', 'jeringa', 1),
  ('Resina fotocurable', 'jeringa', 1),
  ('Resina fotocurable A1', 'jeringa', 1),
  ('Resina fotocurado A1 Body', 'jeringa', 1),
  ('Resina fotocurado A2 Body', 'jeringa', 1),
  ('Resina fotocurado A3 Body', 'jeringa', 1),
  ('Resina fotocurado B2 Body', 'jeringa', 1),
  ('Resina fotocurado Dentin A3', 'jeringa', 1),
  ('Resina fotocurado Enamel A1', 'jeringa', 1),
  ('Resina One Bulk Fill Restorative A3', 'jeringa', 1),
  ('Resina Opalis', 'jeringa', 1),
  ('Resina Orthocem', 'jeringa', 1),
  ('Resina Tetric A1', 'jeringa', 1),
  ('Resina Tetric A2', 'jeringa', 1),
  ('Resina Tetric A3', 'jeringa', 1),
  ('Resina Tetric A3.5', 'jeringa', 1),
  ('Resina Tetric Ceram A1', 'jeringa', 1),
  ('Resina Tetric Ceram A2', 'jeringa', 1),
  ('Resina Tetric Ceram B2', 'jeringa', 1),
  ('Resina translúcida', 'jeringa', 1),
  ('Resina Universal A2', 'jeringa', 1),
  ('Revelador de placa', 'frasco', 1),
  ('RX oclusal', 'unidad', 1),
  ('RX periapical adulto', 'unidad', 1),
  ('RX periapical niño', 'unidad', 1),
  ('Sellante', 'jeringa', 1),
  ('Sellante 3M', 'jeringa', 1),
  ('Sellante Climpro', 'jeringa', 1),
  ('Silano', 'frasco', 1),
  ('Silicona Coltene', 'kit', 1),
  ('Silicona de adición', 'kit', 1),
  ('Silicona de adición + fluida', 'kit', 1),
  ('Silicona de adición Panasil', 'kit', 1),
  ('Silicona de adición pesada', 'kit', 1),
  ('Silicona de condensación pesada', 'kit', 1),
  ('Silicona de condensación Z-Plus', 'kit', 1),
  ('Silicona Elite Glass', 'kit', 1),
  ('Silicona Elite HD Busetcarn', 'kit', 1),
  ('Silicona Elite HD Light', 'kit', 1),
  ('Silicona Elite HD Super Light', 'kit', 1),
  ('Silicona fluida Medium Body', 'kit', 1),
  ('Silicona fluida Regular Body', 'kit', 1),
  ('Silicona Futar', 'kit', 1),
  ('Silicona HD Azul', 'kit', 1),
  ('Silicona HD Morado Regular Body', 'kit', 1),
  ('Silicona HD Regular Light Body', 'kit', 1),
  ('Silicona Light Adición', 'kit', 1),
  ('Silicona pesada', 'kit', 1),
  ('Silicona pesada Z-Plus', 'kit', 1),
  ('Sobres de esterilización', 'paquete', 1),
  ('Soldadura de plata', 'rollo', 1),
  ('Spidlex Silicona', 'kit', 1),
  ('Suero fisiológico', 'frasco', 1),
  ('Teflón', 'rollo', 1),
  ('TheraCal', 'kit', 1),
  ('Tiras de lija para resina', 'tira', 1),
  ('Top Dam', 'frasco', 1),
  ('Tubos', 'unidad', 1),
  ('Tubos linguales', 'unidad', 1),
  ('Tubos mixtos', 'unidad', 1),
  ('Tubos triples', 'unidad', 1),
  ('Vaselina', 'frasco', 1),
  ('Vaso descartable', 'paquete', 1),
  ('Visacril', 'kit', 1),
  ('Yeso azul', 'bolsa', 1),
  ('Yeso extraduro', 'bolsa', 1),
  ('Yeso ortodoncia', 'bolsa', 1),
  ('Yeso París', 'bolsa', 1),
  ('Yeso piedra', 'bolsa', 1),
  ('Yeso tipo III', 'bolsa', 1),
  ('Yeso tipo IV', 'bolsa', 1),
  ('Yodo povidona', 'frasco', 1),
  ('Zirclean', 'frasco', 1),
  ('Z-Prime', 'frasco', 1);
