-- ============================================================
-- V6__seed_tratamientos_pred.sql
-- Los tratamientos predefinidos y la demo data (docentes,
-- operadores, pacientes, unidades 2-6) fueron removidos.
-- La app inicia con el catalogo de materiales (V2) y la
-- unidad 1. Los demas datos los registra el usuario.
-- Los tratamientos predefinidos se re-seedearan en una fase
-- posterior, junto con sus materiales asociados.
-- ============================================================
